In [2]:
import yfinance as yf

In [5]:
ticker = yf.Ticker('AAPL')

In [4]:
??yf.Ticker

Init signature: yf.Ticker(ticker, session=None)
Docstring:      <no docstring>
Source:
class Ticker(TickerBase):
    def __init__(self, ticker, session=None):
        super(Ticker, self).__init__(ticker, session=session)
        self._expirations = {}
        self._underlying  = {}

    def __repr__(self):
        return f'yfinance.Ticker object <{self.ticker}>'

    def _download_options(self, date=None):
        if date is None:
            url = f"{_BASE_URL_}/v7/finance/options/{self.ticker}"
        else:
            url = f"{_BASE_URL_}/v7/finance/options/{self.ticker}?date={date}"

        r = self._data.get(url=url).json()
        if len(r.get('optionChain', {}).get('result', [])) > 0:
            for exp in r['optionChain']['result'][0]['expirationDates']:
                self._expirations[_pd.Timestamp(exp, unit='s').strftime('%Y-%m-%d')] = exp

            self._underlying = r['optionChain']['result'][0].get('quote', {})

            opt = r['optionChain']['result'][0].get('options', [])

            return dict(**opt[0],underlying=self._underlying) if len(opt) > 0 else {}
        return {}

    def _options2df(self, opt, tz=None):
        data = _pd.DataFrame(opt).reindex(columns=[
            'contractSymbol',
            'lastTradeDate',
            'strike',
            'lastPrice',
            'bid',
            'ask',
            'change',
            'percentChange',
            'volume',
            'openInterest',
            'impliedVolatility',
            'inTheMoney',
            'contractSize',
            'currency'])

        data['lastTradeDate'] = _pd.to_datetime(
            data['lastTradeDate'], unit='s', utc=True)
        if tz is not None:
            data['lastTradeDate'] = data['lastTradeDate'].dt.tz_convert(tz)
        return data

    def option_chain(self, date=None, tz=None):
        if date is None:
            options = self._download_options()
        else:
            if not self._expirations:
                self._download_options()
            if date not in self._expirations:
                raise ValueError(
                    f"Expiration `{date}` cannot be found. "
                    f"Available expirations are: [{', '.join(self._expirations)}]")
            date = self._expirations[date]
            options = self._download_options(date)

        if not options:
            return _namedtuple('Options', ['calls', 'puts', 'underlying'])(**{
                "calls": None, "puts": None, "underlying": None
            })

        return _namedtuple('Options', ['calls', 'puts', 'underlying'])(**{
            "calls": self._options2df(options['calls'], tz=tz),
            "puts": self._options2df(options['puts'], tz=tz),
            "underlying": options['underlying']
        })

    # ------------------------

    @property
    def isin(self):
        return self.get_isin()

    @property
    def major_holders(self) -> _pd.DataFrame:
        return self.get_major_holders()

    @property
    def institutional_holders(self) -> _pd.DataFrame:
        return self.get_institutional_holders()

    @property
    def mutualfund_holders(self) -> _pd.DataFrame:
        return self.get_mutualfund_holders()

    @property
    def insider_purchases(self) -> _pd.DataFrame:
        return self.get_insider_purchases()

    @property
    def insider_transactions(self) -> _pd.DataFrame:
        return self.get_insider_transactions()

    @property
    def insider_roster_holders(self) -> _pd.DataFrame:
        return self.get_insider_roster_holders()

    @property
    def dividends(self) -> _pd.Series:
        return self.get_dividends()

    @property
    def capital_gains(self) -> _pd.Series:
        return self.get_capital_gains()

    @property
    def splits(self) -> _pd.Series:
        return self.get_splits()

    @property
    def actions(self) -> _pd.DataFrame:
        return self.get_actions()

    @property
    def shares(self) -> _pd.DataFrame:
        return self.get_shares()

    @property
    def info(self) -> dict:
        return self.get_info()

    @property
    def fast_info(self):
        return self.get_fast_info()

    @property
    def valuation(self) -> _pd.DataFrame:
        return self.get_valuation_measures()

    @property
    def calendar(self) -> dict:
        """
        Returns a dictionary of events, earnings, and dividends for the ticker
        """
        return self.get_calendar()

    @property
    def sec_filings(self) -> dict:
        return self.get_sec_filings()

    @property
    def recommendations(self):
        return self.get_recommendations()

    @property
    def recommendations_summary(self):
        return self.get_recommendations_summary()

    @property
    def upgrades_downgrades(self):
        return self.get_upgrades_downgrades()

    @property
    def earnings(self) -> _pd.DataFrame:
        return self.get_earnings()

    @property
    def quarterly_earnings(self) -> _pd.DataFrame:
        return self.get_earnings(freq='quarterly')

    @property
    def income_stmt(self) -> _pd.DataFrame:
        return self.get_income_stmt(pretty=True)

    @property
    def quarterly_income_stmt(self) -> _pd.DataFrame:
        return self.get_income_stmt(pretty=True, freq='quarterly')

    @property
    def ttm_income_stmt(self) -> _pd.DataFrame:
        return self.get_income_stmt(pretty=True, freq='trailing')

    @property
    def incomestmt(self) -> _pd.DataFrame:
        return self.income_stmt

    @property
    def quarterly_incomestmt(self) -> _pd.DataFrame:
        return self.quarterly_income_stmt

    @property
    def ttm_incomestmt(self) -> _pd.DataFrame:
        return self.ttm_income_stmt

    @property
    def financials(self) -> _pd.DataFrame:
        return self.income_stmt

    @property
    def quarterly_financials(self) -> _pd.DataFrame:
        return self.quarterly_income_stmt

    @property
    def ttm_financials(self) -> _pd.DataFrame:
        return self.ttm_income_stmt

    @property
    def balance_sheet(self) -> _pd.DataFrame:
        return self.get_balance_sheet(pretty=True)

    @property
    def quarterly_balance_sheet(self) -> _pd.DataFrame:
        return self.get_balance_sheet(pretty=True, freq='quarterly')

    @property
    def balancesheet(self) -> _pd.DataFrame:
        return self.balance_sheet

    @property
    def quarterly_balancesheet(self) -> _pd.DataFrame:
        return self.quarterly_balance_sheet

    @property
    def cash_flow(self) -> _pd.DataFrame:
        return self.get_cash_flow(pretty=True, freq="yearly")

    @property
    def quarterly_cash_flow(self) -> _pd.DataFrame:
        return self.get_cash_flow(pretty=True, freq='quarterly')

    @property
    def ttm_cash_flow(self) -> _pd.DataFrame:
        return self.get_cash_flow(pretty=True, freq='trailing')

    @property
    def cashflow(self) -> _pd.DataFrame:
        return self.cash_flow

    @property
    def quarterly_cashflow(self) -> _pd.DataFrame:
        return self.quarterly_cash_flow

    @property
    def ttm_cashflow(self) -> _pd.DataFrame:
        return self.ttm_cash_flow

    @property
    def analyst_price_targets(self) -> dict:
        return self.get_analyst_price_targets()

    @property
    def earnings_estimate(self) -> _pd.DataFrame:
        return self.get_earnings_estimate()

    @property
    def revenue_estimate(self) -> _pd.DataFrame:
        return self.get_revenue_estimate()

    @property
    def earnings_history(self) -> _pd.DataFrame:
        return self.get_earnings_history()

    @property
    def eps_trend(self) -> _pd.DataFrame:
        return self.get_eps_trend()

    @property
    def eps_revisions(self) -> _pd.DataFrame:
        return self.get_eps_revisions()

    @property
    def growth_estimates(self) -> _pd.DataFrame:
        return self.get_growth_estimates()

    @property
    def sustainability(self) -> _pd.DataFrame:
        return self.get_sustainability()

    @property
    def options(self) -> tuple:
        if not self._expirations:
            self._download_options()
        return tuple(self._expirations.keys())

    @property
    def news(self) -> list:
        return self.get_news()

    @property
    def earnings_dates(self) -> _pd.DataFrame:
        return self.get_earnings_dates()

    @property
    def history_metadata(self) -> dict:
        return self.get_history_metadata()

    @property
    def funds_data(self) -> FundsData:
        return self.get_funds_data()
File:           ~/PyCharmMiscProject/.venv/lib/python3.13/site-packages/yfinance/ticker.py
Type:           type
Subclasses:

In [8]:
ticker.info['forwardPE']

30.066742

In [9]:
ticker.analyst_price_targets

{'current': 287.44,
 'high': 355.0,
 'low': 215.0,
 'mean': 303.3762,
 'median': 310.0}

In [10]:
ticker.quarterly_balance_sheet

,2026-03-31,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30
Ordinary Shares Number,1.466769e+10,1.469793e+10,1.477326e+10,1.485672e+10,1.493932e+10,NaN,NaN
Share Issued,1.466769e+10,1.469793e+10,1.477326e+10,1.485672e+10,1.493932e+10,NaN,NaN
Net Debt,3.913900e+10,4.519200e+10,6.272300e+10,6.542900e+10,7.002400e+10,NaN,NaN
Total Debt,8.471100e+10,9.050900e+10,9.865700e+10,1.016980e+11,9.818600e+10,NaN,NaN
Tangible Book Value,8.515700e+10,8.819000e+10,7.373300e+10,6.583000e+10,6.679600e+10,NaN,NaN
...,...,...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,6.850700e+10,6.690700e+10,5.469700e+10,5.537200e+10,4.849800e+10,NaN,NaN
Other Short Term Investments,2.293500e+10,2.159000e+10,1.876300e+10,1.910300e+10,2.033600e+10,NaN,NaN
Cash And Cash Equivalents,4.557200e+10,4.531700e+10,3.593400e+10,3.626900e+10,2.816200e+10,NaN,NaN
Cash Equivalents,1.583200e+10,1.449100e+10,7.667000e+09,9.583000e+09,3.101000e+09,NaN,NaN
Cash Financial,2.974000e+10,3.082600e+10,2.826700e+10,2.668600e+10,2.506100e+10,NaN,NaN

In [11]:
ticker.news

[{'id': '0848f927-f263-4e61-85c0-e546d5c3e178',
  'content': {'id': '0848f927-f263-4e61-85c0-e546d5c3e178',
   'contentType': 'STORY',
   'title': 'Tech stocks today: Broadcom stock falls as chip deal with OpenAI hits speedbump, Musk-Altman court battle continues',
   'description': '',
   'summary': 'Tech stocks are in focus amid an earnings bonanza, layoffs, and AI spending plans.',
   'pubDate': '2026-05-04T10:00:00Z',
   'displayTime': '2026-05-07T19:26:11Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2025-12/9ef20e10-d759-11f0-a36d-78d5b5887396',
    'originalWidth': 4571,
    'originalHeight': 3046,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Z0oJQc3rWK87SnLrO_B5yw--~B/aD0zMDQ2O3c9NDU3MTthcHBpZD15dGFjaHlvbg--/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2025-12/9ef20e10-d759-11f0-a36d-78d5b5887396',
      'width': 4571,
      'height': 3046,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/yNFm_Hc2_wpSBPzldy9pSQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2025-12/9ef20e10-d759-11f0-a36d-78d5b5887396',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/live/tech-stocks-today-semiconductor-earnings-ai-boom-musk-altman-fight-100000447.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/live/tech-stocks-today-semiconductor-earnings-ai-boom-musk-altman-fight-100000447.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '5c34e6b6-0fb7-47e2-b523-29be96197888',
  'content': {'id': '5c34e6b6-0fb7-47e2-b523-29be96197888',
   'contentType': 'STORY',
   'title': "Apple helps 'Magnificent 7' shake off its bear market scare",
   'description': '',
   'summary': "The stock market's biggest trade just woke back up.",
   'pubDate': '2026-05-07T16:21:34Z',
   'displayTime': '2026-05-07T16:21:34Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/yPePRw7qBsjh7z3aDrkONQ--~B/aD0yMzM0O3c9MzUwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-05/341022fd-0783-4d26-9918-d3a2860288f3',
    'originalWidth': 3500,
    'originalHeight': 2334,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/yPePRw7qBsjh7z3aDrkONQ--~B/aD0yMzM0O3c9MzUwMDthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/2026-05/341022fd-0783-4d26-9918-d3a2860288f3',
      'width': 3500,
      'height': 2334,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/e_mxgIGCD0RDiS802pCSxA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/2026-05/341022fd-0783-4d26-9918-d3a2860288f3',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/',
    'sourceId': 'yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/markets/article/apple-helps-magnificent-7-shake-off-its-bear-market-scare-162134523.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/article/apple-helps-magnificent-7-shake-off-its-bear-market-scare-162134523.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '50317d82-5aa0-3f61-9619-e23b80fd4482',
  'content': {'id': '50317d82-5aa0-3f61-9619-e23b80fd4482',
   'contentType': 'STORY',
   'title': "Some iPhone Owners Could Get Payouts Under a $250M Settlement—Here's What You Need to Know",
   'description': '',
   'summary': 'Apple agreed to a $250 million settlement that could mean payouts for some iPhone owners.',
   'pubDate': '2026-05-07T19:04:39Z',
   'displayTime': '2026-05-07T19:04:39Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/investopedia_245/dbd99aa60ef4df6a8e20eaef209d23f4',
    'originalWidth': 4000,
    'originalHeight': 3000,
    'caption': 'Millions of iPhone owners could be eligible for a payment soon as part of the settlement.Credit: Jason Henry / Bloomberg / Getty Images',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/hwE6APMCdzKNNOWL6pon5w--~B/aD0zMDAwO3c9NDAwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/investopedia_245/dbd99aa60ef4df6a8e20eaef209d23f4',
      'width': 4000,
      'height': 3000,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/Nb0BR1v6wwqnIhwz1p.sXw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/investopedia_245/dbd99aa60ef4df6a8e20eaef209d23f4',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Investopedia',
    'url': 'https://www.investopedia.com/',
    'sourceId': 'investopedia_245'},
   'canonicalUrl': {'url': 'https://www.investopedia.com/some-iphone-owners-could-get-payouts-soon-under-a-usd250m-settlement-here-is-what-you-need-to-know-apple-11969182',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/iphone-owners-could-payouts-under-190439712.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '557e85b2-771f-3e79-9b30-777536aafec9',
  'content': {'id': '557e85b2-771f-3e79-9b30-777536aafec9',
   'contentType': 'STORY',
   'title': 'EWT, EWY, and SOXX: The Only 3 ETFs You Need for Semiconductor Dominance',
   'description': '',
   'summary': 'Taiwan and South Korea sit at the center of the global chip supply chain, and three exchange-traded funds offer the most direct way to hold that exposure: the iShares MSCI Taiwan ETF (NYSEARCA:EWT), the iShares MSCI South Korea ETF (NYSEARCA:EWY), and the iShares Semiconductor ETF (NASDAQ:SOXX). Taiwan Semiconductor Manufacturing sits at the center of the ... EWT, EWY, and SOXX: The Only 3 ETFs You Need for Semiconductor Dominance',
   'pubDate': '2026-05-07T18:57:03Z',
   'displayTime': '2026-05-07T18:57:03Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/d7839e36475db9eb4824b577c4fab905',
    'originalWidth': 1366,
    'originalHeight': 768,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/ngDTB6bSrzimq.AxiAI1mg--~B/aD03Njg7dz0xMzY2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/24_7_wall_st__718/d7839e36475db9eb4824b577c4fab905',
      'width': 1366,
      'height': 768,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/.xQcmGYiTejMhJvTEl6e9Q--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/d7839e36475db9eb4824b577c4fab905',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/',
    'sourceId': '24_7_wall_st__718'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/05/07/ewt-ewy-and-soxx-the-only-3-etfs-you-need-for-semiconductor-dominance/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/ewt-ewy-soxx-only-3-185703029.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'a0e94489-6dd8-3443-bb53-f3ef388ec897',
  'content': {'id': 'a0e94489-6dd8-3443-bb53-f3ef388ec897',
   'contentType': 'STORY',
   'title': 'These Stocks Are Today’s Movers: IonQ, Arm, Datadog, Fortinet, Nvidia, Whirlpool, Planet Fitness, Fastly, and More',
   'description': '',
   'summary': 'Arm stock falls as the semiconductor company suggests it may not be able to meet surging demand for its new chip.',
   'pubDate': '2026-05-07T18:42:00Z',
   'displayTime': '2026-05-07T18:42:00Z',
   'isHosted': False,
   'bypassModal': False,
   'previewUrl': 'https://finance.yahoo.com/m/a0e94489-6dd8-3443-bb53-f3ef388ec897/these-stocks-are-today%E2%80%99s.html',
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/Barrons.com/82f4486dca63f849767e3a7a590c1d20',
    'originalWidth': 1280,
    'originalHeight': 640,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/gs50PosAmxJz_pwQTYga4Q--~B/aD02NDA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Barrons.com/82f4486dca63f849767e3a7a590c1d20',
      'width': 1280,
      'height': 640,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/2a0IJt5ezRBhr9ySHzyM9Q--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/Barrons.com/82f4486dca63f849767e3a7a590c1d20',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Barrons.com',
    'url': 'http://www.barrons.com/',
    'sourceId': 'Barrons.com'},
   'canonicalUrl': {'url': 'https://www.barrons.com/articles/stock-movers-4a18446f?siteid=yhoof2&yptr=yahoo',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': None,
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'e195d1cf-0e64-37fb-b0f2-1b19277da6fc',
  'content': {'id': 'e195d1cf-0e64-37fb-b0f2-1b19277da6fc',
   'contentType': 'STORY',
   'title': 'Apple’s Camera-Equipped AirPods Reach Late\xa0Testing in AI Device Push',
   'description': '',
   'summary': '(Bloomberg) -- Apple Inc. has reached the late stages of development for new AirPods with built-in cameras, a significant milestone for what will likely be its first wearable device designed for the artificial intelligence era.Most Read from BloombergBillionaire Duke of Westminster to Sell £700 Million of US Real Estate AssetsUS Has Opened a Passage Through Hormuz, Central Command SaysDOJ Plans Intervention in Trump Supreme Court Carroll AppealChina Asks Banks to Pause New Loans to US-Sanctioned',
   'pubDate': '2026-05-07T18:20:31Z',
   'displayTime': '2026-05-07T18:20:31Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/bloomberg_holding_pen_162/f7838f1781e8b8b0d682aa826236b361',
    'originalWidth': 2000,
    'originalHeight': 1333,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/w6ClsJpn2F3ONWXAkB9qvA--~B/aD0xMzMzO3c9MjAwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/bloomberg_holding_pen_162/f7838f1781e8b8b0d682aa826236b361',
      'width': 2000,
      'height': 1333,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/.N0Uq3A78vdjEsLAT4p0xw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/bloomberg_holding_pen_162/f7838f1781e8b8b0d682aa826236b361',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Bloomberg',
    'url': 'https://www.bloomberg.com/company',
    'sourceId': 'bloomberg_holding_pen_162'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/articles/apple-camera-equipped-airpods-reach-182031892.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/articles/apple-camera-equipped-airpods-reach-182031892.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '46b5195c-43ac-35af-95bc-943ca72dcd67',
  'content': {'id': '46b5195c-43ac-35af-95bc-943ca72dcd67',
   'contentType': 'STORY',
   'title': 'Apple at $284: Buy, Sell or Hold?',
   'description': '',
   'summary': 'At $284, Apple (NASDAQ:AAPL) looks compelling at current levels. The iPhone maker just posted its best March quarter ever and is pressing against its 52-week high. Apple sits atop the consumer electronics industry with 2.5 billion active devices and a market cap near $4.17 trillion. Shares have rallied 11.04% over the past month and 43.5% ... Apple at $284: Buy, Sell or Hold?',
   'pubDate': '2026-05-07T16:35:51Z',
   'displayTime': '2026-05-07T16:35:51Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/24_7_wall_st__718/ccd8d8423823aac13ad8c6f95f838fdd',
    'originalWidth': 2560,
    'originalHeight': 1707,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/F4BmHJiQnSMvr6fQFdQCgg--~B/aD0xNzA3O3c9MjU2MDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/24_7_wall_st__718/ccd8d8423823aac13ad8c6f95f838fdd',
      'width': 2560,
      'height': 1707,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/fQncwsnHp9sKTkY4PnIk4Q--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/24_7_wall_st__718/ccd8d8423823aac13ad8c6f95f838fdd',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': '24/7 Wall St.',
    'url': 'https://247wallst.com/',
    'sourceId': '24_7_wall_st__718'},
   'canonicalUrl': {'url': 'https://247wallst.com/investing/2026/05/07/apple-at-284-buy-sell-or-hold/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/apple-284-buy-sell-hold-163551086.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'cb83fd42-f698-3aa7-bcfb-4d8e7a81b48b',
  'content': {'id': 'cb83fd42-f698-3aa7-bcfb-4d8e7a81b48b',
   'contentType': 'STORY',
   'title': 'What Long-Term Investors Should Know Before Buying This Broad Market ETF',
   'description': '',
   'summary': "Just because a fund holds hundreds or even thousands of stocks doesn't mean it's diversified.",
   'pubDate': '2026-05-07T16:35:00Z',
   'displayTime': '2026-05-07T16:35:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/155c35411f6823c738ea9ab2bd6bbd47',
    'originalWidth': 1400,
    'originalHeight': 933,
    'caption': 'An investor examining financial statements.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/ikFCNLLRJ.Ne_OtuEe7ljQ--~B/aD05MzM7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/155c35411f6823c738ea9ab2bd6bbd47',
      'width': 1400,
      'height': 933,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/rKvl3MfiH5GjCoQACvTfmg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/155c35411f6823c738ea9ab2bd6bbd47',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/05/07/what-investors-should-know-buying-vti-etf/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/long-term-investors-know-buying-163500045.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'fd11e686-9a45-3110-a645-b1c9776a10cf',
  'content': {'id': 'fd11e686-9a45-3110-a645-b1c9776a10cf',
   'contentType': 'STORY',
   'title': 'This Sneaky AI Play Nearly Doubled Sales. The Stock Is Rising Sharply.',
   'description': '',
   'summary': 'Shares of  SiTime  spiked Thursday after the maker of timing solutions nearly doubled revenue from last year, reflecting strong demand from artificial-intelligence data centers.  After the closing bell Wednesday, SiTime reported adjusted earnings of $1.44 a share for the first quarter, up from 26 cents a year ago and well above analysts’ consensus estimates of $1.16.  The company introduced a full-year revenue growth forecast of at least 80%.',
   'pubDate': '2026-05-07T15:53:00Z',
   'displayTime': '2026-05-07T15:53:00Z',
   'isHosted': False,
   'bypassModal': False,
   'previewUrl': 'https://finance.yahoo.com/m/fd11e686-9a45-3110-a645-b1c9776a10cf/this-sneaky-ai-play-nearly.html',
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/Barrons.com/060437a85bb0c61d1c459b1c05a16586',
    'originalWidth': 1280,
    'originalHeight': 640,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/hMuTegOSVAx6TOZWPKuVCw--~B/aD02NDA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Barrons.com/060437a85bb0c61d1c459b1c05a16586',
      'width': 1280,
      'height': 640,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/k8UBHfEFRhVpotZdXjIUdw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/Barrons.com/060437a85bb0c61d1c459b1c05a16586',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Barrons.com',
    'url': 'http://www.barrons.com/',
    'sourceId': 'Barrons.com'},
   'canonicalUrl': {'url': 'https://www.barrons.com/articles/sitime-earnings-stock-price-01b0c2df?siteid=yhoof2&yptr=yahoo',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': None,
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '91e08e3c-5dd1-3620-b2ab-1c7bb660ed3b',
  'content': {'id': '91e08e3c-5dd1-3620-b2ab-1c7bb660ed3b',
   'contentType': 'STORY',
   'title': 'True North Boosts Flexible Bond Position by $6 Million Amid Rate Volatility',
   'description': '',
   'summary': 'TCW Flexible Income ETF pursues high current income and long-term growth through an actively managed, diversified fixed income portfolio.',
   'pubDate': '2026-05-07T15:35:55Z',
   'displayTime': '2026-05-07T15:35:55Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/0b1c16594f294f2b49d3c011f91210d1',
    'originalWidth': 800,
    'originalHeight': 714,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/L8SfsYJFAxzSjaUYaJ4MIQ--~B/aD03MTQ7dz04MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/0b1c16594f294f2b49d3c011f91210d1',
      'width': 800,
      'height': 714,
      'tag': 'original'},

In [12]:
ticker.calendar

{'Dividend Date': datetime.date(2026, 5, 14),
 'Ex-Dividend Date': datetime.date(2026, 5, 11),
 'Earnings Date': [datetime.date(2026, 7, 30)],
 'Earnings High': 1.99,
 'Earnings Low': 1.83,
 'Earnings Average': 1.89077,
 'Revenue High': 112000000000,
 'Revenue Low': 107501000000,
 'Revenue Average': 108790845560}

In [15]:
ticker.history(period = '2y')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-05-08 00:00:00-04:00,181.200927,181.418945,179.813545,181.091919,45057100,0.00,0.0
2024-05-09 00:00:00-04:00,180.913544,182.994611,180.467605,182.905426,48983000,0.00,0.0
2024-05-10 00:00:00-04:00,183.480965,183.669509,180.732235,181.645172,50759500,0.25,0.0
2024-05-13 00:00:00-04:00,184.016807,185.664071,183.203093,184.850357,72044800,0.00,0.0
2024-05-14 00:00:00-04:00,186.070904,186.854849,184.860266,185.991516,52393600,0.00,0.0
...,...,...,...,...,...,...,...
2026-05-01 00:00:00-04:00,278.859985,287.220001,278.369995,280.140015,79915400,0.00,0.0
2026-05-04 00:00:00-04:00,279.660004,280.630005,274.859985,276.829987,46668400,0.00,0.0
2026-05-05 00:00:00-04:00,276.929993,284.570007,276.500000,284.179993,49311700,0.00,0.0
2026-05-06 00:00:00-04:00,281.920013,288.029999,281.070007,287.510010,58336100,0.00,0.0
2026-05-07 00:00:00-04:00,289.269989,292.130005,285.779999,287.440002,40410371,0.00,0.0

In [17]:
ticker.options

('2026-05-08',
 '2026-05-11',
 '2026-05-13',
 '2026-05-15',
 '2026-05-18',
 '2026-05-20',
 '2026-05-22',
 '2026-05-29',
 '2026-06-05',
 '2026-06-12',
 '2026-06-18',
 '2026-07-17',
 '2026-08-21',
 '2026-09-18',
 '2026-10-16',
 '2026-11-20',
 '2026-12-18',
 '2027-01-15',
 '2027-03-19',
 '2027-06-17',
 '2027-12-17',
 '2028-01-21',
 '2028-03-17',
 '2028-12-15')

In [20]:
ticker.option_chain(ticker.options[0]).calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260508C00110000,2026-05-01 15:08:41+00:00,110.0,172.17,175.15,177.55,0.000000,0.000000,2.0,2,5.070316,True,REGULAR,USD
1,AAPL260508C00135000,2026-05-07 17:07:53+00:00,135.0,153.73,150.15,153.65,12.029999,8.489766,3.0,1,5.714847,True,REGULAR,USD
2,AAPL260508C00140000,2026-05-07 18:22:56+00:00,140.0,149.09,145.55,148.40,7.009995,4.933836,26.0,2,5.246097,True,REGULAR,USD
3,AAPL260508C00145000,2026-05-07 17:20:30+00:00,145.0,143.74,140.30,143.85,6.639999,4.843180,5.0,70,5.386722,True,REGULAR,USD
4,AAPL260508C00150000,2026-05-07 18:22:56+00:00,150.0,139.17,136.40,138.60,12.549995,9.911542,27.0,3,3.296877,True,REGULAR,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,AAPL260508C00365000,2026-04-21 19:45:35+00:00,365.0,0.03,0.00,0.01,0.000000,0.000000,NaN,20,1.000005,False,REGULAR,USD
60,AAPL260508C00385000,2026-04-30 19:59:42+00:00,385.0,0.02,0.00,0.01,0.000000,0.000000,NaN,2,1.218754,False,REGULAR,USD
61,AAPL260508C00390000,2026-05-01 13:42:43+00:00,390.0,0.13,0.00,0.01,0.000000,0.000000,5.0,16,1.281254,False,REGULAR,USD
62,AAPL260508C00395000,2026-05-01 17:45:56+00:00,395.0,0.01,0.00,0.01,0.000000,0.000000,29.0,29,1.312503,False,REGULAR,USD
63,AAPL260508C00400000,2026-05-07 14:47:11+00:00,400.0,0.01,0.00,0.01,-0.030000,-75.000000,3.0,2,1.375003,False,REGULAR,USD